<?php
/**
 * MessengerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Мессенджер
 *
 * API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).**
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessengerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessengerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for chatRead
     *
     * Прочитать чат.
     *
     */
    public function testChatRead()
    {
    }

    /**
     * Test case for deleteMessage
     *
     * Удаление сообщения.
     *
     */
    public function testDeleteMessage()
    {
    }

    /**
     * Test case for getChatByIdV2
     *
     * Получение информации по чату.
     *
     */
    public function testGetChatByIdV2()
    {
    }

    /**
     * Test case for getChatsV2
     *
     * Получение информации по чатам.
     *
     */
    public function testGetChatsV2()
    {
    }

    /**
     * Test case for getMessagesV3
     *
     * Получение списка сообщений V3.
     *
     */
    public function testGetMessagesV3()
    {
    }

    /**
     * Test case for getSubscriptions
     *
     * Получение подписок (webhooks).
     *
     */
    public function testGetSubscriptions()
    {
    }

    /**
     * Test case for postBlacklistV2
     *
     * Добавление пользователя в blacklist.
     *
     */
    public function testPostBlacklistV2()
    {
    }

    /**
     * Test case for postSendMessage
     *
     * Отправление сообщения.
     *
     */
    public function testPostSendMessage()
    {
    }

    /**
     * Test case for postWebhookUnsubscribe
     *
     * Отключение уведомлений (webhooks).
     *
     */
    public function testPostWebhookUnsubscribe()
    {
    }

    /**
     * Test case for postWebhookV3
     *
     * Включение уведомлений V3 (webhooks).
     *
     */
    public function testPostWebhookV3()
    {
    }
}
